[Interface]
PrivateKey = If+FRwdW5hnx7uY/FSgkWwpiaJhLs43xc8FiEVnsuok=
Address = 10.0.0.2/32
DNS = 1.1.1.1, 1.0.0.1
MTU = 1420

# sivov-1
[Peer]
PublicKey = eNpNfBLps6XTk6+kmqrjzzw1DWD5TxiOu+rMRWUd3qE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 194.5.79.26:47431
